import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: '/Yamagotchi/', // Cambia 'Yamagotchi' por el nombre exacto de tu repositorio
  build: {
    outDir: 'dist',
  }
})
